[package]
name = "forge_walker"
version = "0.1.0"
edition = "2021"

[dependencies]
ignore = "0.4.23"
tokio = { version = "1.42.0", features = ["fs"] }
thiserror = "2.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
