[package]
name = "forge_inte"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
forge_api = { path = "../forge_api" }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
