[package]
name = "forge_env"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["from"] }
handlebars = "6.2.0"
serde = "1.0.216"
dirs = "5.0.1"
forge_walker = { path = "../forge_walker" }
derive_setters = "0.1.6"
