[package]
name = "forge_main"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
forge_app = { path = "../forge_app" }
forge_domain = { path = "../forge_domain" }
forge_walker = { path = "../forge_walker" }
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1.17"
colored = "3.0.0"
crossterm = { version = "0.28", features = ["event-stream"] }
async-trait = "0.1"
inquire = "0.7.5"
regex = "1.10.2"
strum = "0.26.3"
strum_macros = "0.26.4"
anyhow = "1.0.95"
chrono = "0.4"
derive_setters = "0.1"
lazy_static = "1.4.0"
serde_json = "1.0"
thiserror = "2.0"
reedline = "0.38.0"
nu-ansi-term = "0.50.1"
dirs = "6.0.0"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }

[dev-dependencies]
insta = "1.34.0"
once_cell = "1.19.0"
pretty_assertions = "1.4.1"
tempfile = "3.9.0"
