[package]
name = "forge_snaps"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
forge_fs.workspace = true
forge_walker.workspace = true
blake3.workspace = true

[dev-dependencies]
tempfile = "3.17.1"
tokio = {version = "1.43.0", features = ["full"]}
