[package]
name = "forge_domain"
version = "0.1.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
async-trait = "0.1.84"
chrono = "0.4.39"
derive_more = { version = "1.0.0", features = ["from", "display"] }
derive_setters = "0.1.6"
futures = "0.3.31"
nom = "7.1.3"
quick-xml = { version = "0.37.2", features = ["serialize"] }
schemars = "0.8.21"
serde = "1.0.217"
serde_json = "1.0.134"
strum = "0.26.3"
strum_macros = "0.26.4"
tokio = { version = "1.42.0", features = ["full", "test-util"] }
tokio-stream = "0.1.17"
uuid = "1.11.0"

[dev-dependencies]
insta = { version = "1.34.0", features = ["json"] }
pretty_assertions = "1.4.1"
